version: "3.8"

services:
  postgres:
    container_name: nest-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
